// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package io.lucci.potlatch.model;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

public class UserBuilder extends UserBuilderBase<UserBuilder> {
	public static UserBuilder user() {
		return new UserBuilder();
	}

	public UserBuilder() {
		super(new User());
	}

	public User build() {
		return getInstance();
	}
}

class UserBuilderBase<GeneratorT extends UserBuilderBase<GeneratorT>> {
	private User instance;

	protected UserBuilderBase(User aInstance) {
		instance = aInstance;
	}

	protected User getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUsername(String aValue) {
		instance.setUsername(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPassword(String aValue) {
		instance.setPassword(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBirthdate(Date aValue) {
		instance.setBirthdate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withGender(String aValue) {
		instance.setGender(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withBlockInappropriate(Boolean aValue) {
		instance.setBlockInappropriate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRefreshInterval(Long aValue) {
		instance.setRefreshInterval(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNumberOflikes(Long aValue) {
		instance.setNumberOflikes(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAuthorities(Collection<SimpleGrantedAuthority> aValue) {
		instance.setAuthorities(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedAuthority(SimpleGrantedAuthority aValue) {
		if (instance.getAuthorities() == null) {
			instance.setAuthorities(new ArrayList<SimpleGrantedAuthority>());
		}

		((ArrayList<SimpleGrantedAuthority>) instance.getAuthorities())
				.add(aValue);

		return (GeneratorT) this;
	}
}
