// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package io.lucci.potlatch.client.model;

import java.util.Date;

public class GiftBuilder extends GiftBuilderBase<GiftBuilder> {
	public static GiftBuilder gift() {
		return new GiftBuilder();
	}

	public GiftBuilder() {
		super(new Gift());
	}

	public Gift build() {
		return getInstance();
	}
}

class GiftBuilderBase<GeneratorT extends GiftBuilderBase<GeneratorT>> {
	private Gift instance;

	protected GiftBuilderBase(Gift aInstance) {
		instance = aInstance;
	}

	protected Gift getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUuid(String aValue) {
		instance.setUuid(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTitle(String aValue) {
		instance.setTitle(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDescription(String aValue) {
		instance.setDescription(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTimestamp(Date aValue) {
		instance.setTimestamp(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withChainMaster(Boolean aValue) {
		instance.setChainMaster(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUri(String aValue) {
		instance.setUri(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withStatus(String aValue) {
		instance.setStatus(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNumberOfLikes(Long aValue) {
		instance.setNumberOfLikes(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUser(User aValue) {
		instance.setUser(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withLikedByMe(Boolean aValue) {
		instance.setLikedByMe(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withReportedByMe(Boolean aValue) {
		instance.setReportedByMe(aValue);

		return (GeneratorT) this;
	}
}
